// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjAPICar.Data;

#nullable disable

namespace ProjAPICar.Migrations
{
    [DbContext(typeof(ProjAPICarContext))]
    partial class ProjAPICarContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Generator.Car", b =>
                {
                    b.Property<string>("_licensePlate")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("_color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("_makedYear")
                        .HasColumnType("int");

                    b.Property<int>("_modelYear")
                        .HasColumnType("int");

                    b.Property<string>("_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("_licensePlate");

                    b.ToTable("Car");
                });
#pragma warning restore 612, 618
        }
    }
}
